### ISSUE TITLE
Variable: determine what is the best API for this.

### ISSUE THREAD

**Issue by LemondRinds** [migueldeicaza/TensorFlowSharp#133] opened 2017-08-30 17:02 UTC
https://github.com/migueldeicaza/TensorFlowSharp/blob/30314fdbcf63d79cc147f03a9bb96bae261d0782/SampleTest/SampleTest.cs#L295

Attempting to follow the [basic MNIST tuts from Tensorflow's website](https://www.tensorflow.org/get_started/mnist/beginners). TFGraph Mul operation won't accept TFGraph Variables, found this line in yall's tests and it results in similar issue.

![image](https://user-images.githubusercontent.com/20599319/29885216-0f6628bc-8d84-11e7-97f0-a19f03af93c7.png)
Continuing results in this exception:
{"Inconsistent values for attr 'T' DT_FLOAT vs. DT_RESOURCE while building NodeDef 'Mul0' using Op<name=Mul; signature=x:T, y:T -> z:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, DT_INT8, DT_UINT16, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]; is_commutative=true>"}

Any info on how to approach this? TFGraph Variables are Resource types and apparently can't be Mul'd with Floats, so I'm at a loss as to how this test is supposed to work or how I can go through the tuts on Tensorflow's site.

Forgive my formatting and any ambiguity, I'm new to GitHub and this is out of my realm.

**Comment by migueldeicaza** [comment] 2017-09-04 01:59
This is a current limitation on the TensorFlow bindings for languages other than Python. 

The TensorFlow team is using a capability called "references" which are not supported in the C binding (and by extension C#, Go, Java) and this is required to use the VariableV2 method that is required to make this work properly (and replace the current code that uses VarHandleOp instead).

This is the code that needs the porting:

https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/ops/variables.py#L281

Into this:

https://github.com/migueldeicaza/TensorFlowSharp/blob/6ba299eea1f6c6c9ee9625ae03434628ff8daf07/TensorFlowSharp/OperationsExtras.cs#L109

**Comment by migueldeicaza** [comment] 2017-09-04 02:06
Variables are useful to keep state across invocations to `Run`, if you do not need this, you can just remove the Variable use completely, and just use the constants from your tensor (just make sure the data type is correct, the sample itself was wrong, it was missing a cast to `(float)`).

**Comment by migueldeicaza** [comment] 2017-09-05 02:14
Work in progress patch on the `refsupport` branch.

**Comment by migueldeicaza** [comment] 2017-09-07 02:29
I have an implementation now on a branch, but it regresses some uses of Variable that were able to fetch the values.   I need to finish that work (replace ReadVariableOp with a conversion that turns the regular variable into a handle)

**Comment by migueldeicaza** [comment] 2017-09-08 02:55
Well, I was wrong.   It is not necessary to use the ref support (but it will still come in handy, so I will continue with that code).

The problem is that the "Variable" method with no arguments returns a variable handle and if you want to read the result, you need to call `ReadVariableOp` on the result.   I also have a couple of other overloads that do this work for you, so you can either use `ReadVariableOp`, or use one of the overloads that returns the `out TOutput value` and use the resulting value to read the variable.

That said, this is ugly as sin.   This was based on this Go code:

https://github.com/asimshankar/tensorflow/blob/govars/tensorflow/go/v/var.go

What I probably should do is have a Varibale that returns the tuple and avoids the confusion, rather that provide an overload that give you a false sense of having obtained the right value.

**Comment by migueldeicaza** [comment] 2017-09-08 03:00
I am keeping this bug open to figure out if

**Comment by migueldeicaza** [comment] 2017-09-08 03:05
I am keeping this bug open to figure out what to do about `Variable`, currently the options are:

(a) Introduce `(TFOutput init, TFOutput handle, TFOutput readValue) Variable (...)` returning a tuple with all three handles, or

(b) Merely document that `Variable` returns a VarHandleOp and that reading this requires a call to `ReadVariableOp` or

(c) For the case where Variable is called with simple arguments, create the implicit Read, and return the `ReadVariableOp` instead of the variable itself.

Python has a Variable class, and what we could do is return an instance of a Variable class that itself holds the three nodes (variable, init and read) and provide implicit conversions so the Variable could be used where a TFOutput is used (the implicit conversion would retrieve the variable node).

**Comment by boborp** [comment] 2017-09-11 12:00
Hi, I tried some stuff with variables and I am not sure it is working correctly or I did it wrong. I know it is WiP so could you add this test to the test suite. It just tries to use 2 variables and set different value to each:
`[Fact]
		public void MultipleVariables_InitializedSeparately_HaveSeparateValues ()
		{
			const double W_INIT = 1.0;
			const double b_INIT = -0.3;

			using (var graph = new TFGraph ()) {
				TFOperation initW;
				TFOutput valueW;
				var W = graph.Variable (graph.Const (W_INIT), out initW, out valueW, "W");
				TFOperation initb;
				TFOutput valueb;
				var b = graph.Variable (graph.Const (b_INIT), out initb, out valueb, "b");
				
				double setToW = 0.5;
				var updateW = graph.AssignVariableOp (W, graph.Const (setToW));
				double setTob = 0.1;
				var updateb = graph.AssignVariableOp (b, graph.Const (setTob));
				var readW = graph.ReadVariableOp (W, TFDataType.Double);
				var readb = graph.ReadVariableOp (b, TFDataType.Double);

				using (var sess = new TFSession (graph)) {

					//init W
					sess.GetRunner ().AddTarget (initW).Run ();
					var resultW = sess.GetRunner ().Fetch (valueW).Run ();
					Console.WriteLine ("Value of W: " + resultW [0].GetValue ());
					var resultb = sess.GetRunner ().Fetch (valueb).Run ();
					Console.WriteLine ("Value of b: " + resultb [0].GetValue ());

					Assert.Equal (W_INIT, resultW [0].GetValue ());

					//init b
					sess.GetRunner ().AddTarget (initb).Run ();
					var resultW2 = sess.GetRunner ().Fetch (valueW).Run ();
					Console.WriteLine ("Result of W: " + resultW2 [0].GetValue ());
					var resultb2 = sess.GetRunner ().Fetch (valueb).Run ();
					Console.WriteLine ("Result of b: " + resultb2 [0].GetValue ());

					Assert.Equal (W_INIT, resultW2 [0].GetValue ());
					Assert.Equal (b_INIT, resultb2 [0].GetValue ());

					//update W
					var rsUW = sess.GetRunner ().AddTarget (updateW).Fetch (valueW, valueb).Run ();
					Console.WriteLine ("Value of W: " + rsUW [0].GetValue ());
					Console.WriteLine ("Value of b: " + rsUW [1].GetValue ());

					Assert.Equal (setToW, rsUW [0].GetValue ());
					Assert.Equal (b_INIT, rsUW [1].GetValue ());

					//read b,W
					var readOp = sess.GetRunner ().Fetch (readW, readb).Run ();
					Console.WriteLine ("Read of W: " + readOp [0].GetValue ());
					Console.WriteLine ("Read of b: " + readOp [1].GetValue ());

					Assert.Equal (setToW, readOp [0].GetValue ());
					Assert.Equal (b_INIT, readOp [1].GetValue ());
				}
			}
		}`

I have ended up with both variables always set to the similar value, however I tried.
Thanks and keep up working on this :)

**Comment by LemondRinds** [comment] 2017-09-25 14:44
> (b) Merely document that Variable returns a VarHandleOp and that reading this requires a call to ReadVariableOp or

I'm good with this for the time being, I'll give it a shot later. Only worry is making this behavior super obvious in docs may be a pain for yall to maintain.

> Python has a Variable class, and what we could do is return an instance of a Variable class that itself holds the three nodes (variable, init and read) and provide implicit conversions so the Variable could be used where a TFOutput is used (the implicit conversion would retrieve the variable node).

This sounds good, too, I love implicit conversions! Only wish I could help yall out, but this is all a little out of my league (and idk python). :/

**Comment by migueldeicaza** [comment] 2017-09-26 13:36
Forgot to close this, it was implemented in this commit:

bb50d3a7463158bdb84951610af9946110e53c53

**Closed by migueldeicaza** 2017-09-26 13:36 UTC

**Comment by LemondRinds** [comment] 2017-09-26 13:39
Kewl, thanks. I actually just got Mul to work after casting the const to a float and using readVarOp per your suggestions.

![image](https://user-images.githubusercontent.com/20599319/30863214-7d3e7dec-a29e-11e7-9e44-31d450348ac2.png)

Thanks a bunch, m8! Time to continue with those Tensorflow tuts!
